name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Update Backend Dependencies
      working-directory: ./way-share-backend
      run: |
        npm update
        npm audit fix
    
    - name: Update Frontend Dependencies
      working-directory: ./way-share-frontend
      run: |
        npm update
        npm audit fix
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'chore: update dependencies'
        commit-message: 'chore: update npm dependencies'
        branch: update-dependencies
        delete-branch: true
        body: |
          ## Automated Dependency Updates
          
          This PR contains automatic dependency updates from npm.
          
          Please review the changes and ensure all tests pass before merging.